board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:post_id>/', views.detail, name='detail'),
    path('input/', views.input, name='input'),
    path('create/', views.create, name='create'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('editform/<int:post_id>/', views.editform, name='editform'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
]

board/models.py
from django.db import models

# Create your models here.

class Put (models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    count = models.IntegerField(default=0)
    writer = models.CharField(max_length=30, default='anonymous')
    passwd = models.CharField(max_length=30)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.title

board/forms.py
# from django import forms
# from .models import put
#
# class MemberForm(forms.ModelForm):
#     class Meta:
#         model = put
#         fields = ['name','email','profile']

board/views.py
from django.shortcuts import render, get_object_or_404, redirect,HttpResponse
from django.utils import timezone

from .models import Put
# Create your views here.

def index(request):
    post_list = Put.objects.order_by('-create_date')
    context = {'post_list' : post_list}
    return render(request,'anonym/board_list.html', context)

def detail(request, post_id):
    post = get_object_or_404(Put,pk=post_id)
    context = {'post': post}
    return render(request,'anonym/board_detail.html', context)

def input(request):
    return render(request, 'anonym/board_input.html')

def create(request):
    title = request.POST.get('title')
    content = request.POST.get('content')
    passwd = request.POST.get('passwd')
    writer = request.POST.get('writer')
    new_post = Put(title=title, content=content, passwd=passwd, writer=writer, create_date=timezone.now())
    new_post.save()
    return redirect('board:detail', post_id=new_post.id)

def delete(request,post_id):
    post = get_object_or_404(Put, pk=post_id)
    post.delete()
    return redirect('board:index')

def editform(request,post_id):
    post = get_object_or_404(Put, pk=post_id)
    context = {'post': post}
    return render(request, 'anonym/board_edit.html', context)


def edit(request, post_id):
    post = get_object_or_404(Put, pk=post_id)

    # 폼에서 전달된 값 가져오기
    title = request.POST.get('title', post.title)  # 기본값으로 기존 title 사용
    content = request.POST.get('profile', post.content)  # 기존 내용 사용
    passwd = request.POST.get('passwd', post.passwd)
    writer = request.POST.get('writer', post.writer)

    # 필드 업데이트
    post.title = title
    post.content = content
    post.passwd = passwd
    post.writer = writer

    # 저장
    post.save()

    return redirect('board:detail', post_id=post.id)

templates/anonym/board_detail.html
{% extends 'frame.html' %}

{% block content %}
<div class="container mt-3">
    <h1>게시글 상세 보기</h1>
    <table class="table table-bordered" >
        <tr class="table-dark">
            <td style="width:5%">No.</td>
            <td style="width:5%">{{ forloop.revcounter }}</td>
            <td style="width:5%">제목</td>
            <td style="width:70%">{{ post.title }}</td>
            <td style="width:7%">조회수</td>
            <td>{{ post.count }}</td>
        </tr>
    </table>
    <h2>내용</h2>
    <div>
        <p>{{ post.content }}</p>
    </div>
<a href="{% url 'board:editform' post.id %}" class="btn btn-primary mb-3">수정하기</a>
<a href="{% url 'board:delete' post.id %}" class="btn btn-primary mb-3">삭제</a>
</div>
{% endblock %}

templates/anonym/board_edit.html
{% extends 'frame.html' %}

{% block content %}

<div class="container mt-4">
    <h1>게시글 수정 작성</h1>
    <form method="post" action="{% url 'board:edit' post.id %}">
        {% csrf_token %}
        제목 : <input type="text" name="title" class="form-control" value="{{ post.title }}"><br>
        내용 : <textarea name="profile" class="form-control">{{ post.content }}</textarea><br>
        <div style="display: flex; gap: 10px">
            <div style="flex:1">
            비밀번호 : <input type="text" name="passwd" class="form-control" value="{{ post.passwd }}"><br>
            </div>
            <div style="flex:1">
            작성자 : <input type="text" name="writer" class="form-control" value="{{ post.writer }}"><br>
            </div>
        </div>
        <input type="submit" value="수정확인" class="btn btn-danger">
    </form>
</div>






{% endblock %}

templates/anonym/board_form.html
{% extends 'frame.html' %}

{% block content %}

<div class="container mt-4">
    <h1>게시글 작성</h1>
    <form method="post" action="{% url 'board:create' %}">
        {% csrf_token %}
        제목 : <input type="text" name="title" class="form-control"><br>
        내용 : <textarea name="content" class="form-control"></textarea><br>
        <div style="display: flex; gap: 10px">
            <div style="flex:1">
            비밀번호 : <input type="password" name="passwd" class="form-control"><br>
            </div>
            <div style="flex:1">
            작성자 : <input type="text" name="writer" class="form-control"><br>
            </div>
        </div>
        <input type="submit" value="입력확인" class="btn btn-danger">
    </form>
</div>

{% endblock %}

templates/anonym/board_input.html
{% extends 'frame.html' %}

{% block content %}

<div class="container mt-4">
    <h1>게시글 작성</h1>
    <form method="post" action="{% url 'board:create' %}">
        {% csrf_token %}
        제목 : <input type="text" name="title" class="form-control"><br>
        내용 : <textarea name="content" class="form-control"></textarea><br>
        <div style="display: flex; gap: 10px">
            <div style="flex:1">
            비밀번호 : <input type="password" name="passwd" class="form-control"><br>
            </div>
            <div style="flex:1">
            작성자 : <input type="text" name="writer" class="form-control" value="anonymous"><br>
            </div>
        </div>
        <input type="submit" value="입력확인" class="btn btn-danger">
    </form>
</div>
{% endblock %}

templates/anonym/board_list.html
{% extends 'frame.html' %}

{% block content %}

<div class="container mt-3">
    <a href="{% url 'board:input' %}" class="btn btn-primary mb-3">글쓰기</a>

    <table class="table table-bordered">
        <tr class="table-dark">
            <td style="width:5%">번호</td>
            <td style="width:60%">제목</td>
            <td style="width:10%">작성자</td>
        </tr>
        {% if post_list %}
            {% for post in post_list %}
                <tr>
                    <td>{{ forloop.revcounter }}</td>  <!-- 번호 표시 -->
                    <td><a href="{% url 'board:detail' post.id %}">{{ post.title }}</a></td>  <!-- post 사용 -->
                    <td>{{ post.writer }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">게시글이 없습니다.</td>
            </tr>
        {% endif %}
    </table>
</div>

{% endblock %}

templates/frame.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>board</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'bootstrap.min.js' %}"></script>
</head>
<body>
{% include "menu.html" %}
{% block content %}
{% endblock %}
</body>
</html>

templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <div class="navbar-brand">SECURE CODE</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'board:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">메뉴1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">메뉴2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">메뉴3</a>
        </li>
      </ul>
    </div>
  </div>
</nav>